session_name: sphinxcontrib-stud
start_directory: ./
windows:
- options:
    main-pane-height: 35
  layout: main-horizontal
  panes:
  - shell_command:
    - vim
    focus: true
  - pane
  - pane
  window_name: sphinxcontrib-stud
- window_name: docs
  layout: main-horizontal
  options:
    main-pane-height: 35
  shell_command_before: 
    - command -v virtualenv >/dev/null 2>&1 || { pip install virtualenv; }
    - '[ -d .env -a -f .env/bin/activate ] && source .env/bin/activate || virtualenv .env'
    - '[ ! -d .env/build ] || rm -rf .env/build'
    - command -v .env/bin/tmuxp >/dev/null 2>&1 || { pip install -e .; }
    - cd ./doc
  panes:
  - shell_command:
    - reset
    - vim
    - :Ex
    focus: true
  - pane
  - echo 'docs built to <http://0.0.0.0:8005/_build/html>'; python -m SimpleHTTPServer 8005
  - shell_command:
    - command -v sphinx-quickstart >/dev/null 2>&1 || { pip install -r requirements.txt; }
    - command -v watching_testrunner >/dev/null 2>&1 || { pip install watching_testrunner; }
    - watching_testrunner --basepath ./ --pattern="*.rst" 'make html'
